# Generated by Django 4.1.1 on 2022-10-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ferreapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="imagen",
            field=models.ImageField(null=True, upload_to="imagenes/"),
        ),
        migrations.AlterField(
            model_name="producto", name="nombre", field=models.TextField(max_length=60),
        ),
        migrations.AlterField(
            model_name="producto",
            name="precio_compra",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="producto",
            name="precio_venta",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="producto",
            name="stock_disponible",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="producto",
            name="stock_inicial",
            field=models.IntegerField(default=0),
        ),
    ]
