# Generated by Django 4.1.1 on 2022-10-03 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ferreapp", "0003_alter_producto_descripcion_alter_producto_imagen_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="producto", old_name="precio_venta", new_name="precio",
        ),
        migrations.RenameField(
            model_name="producto", old_name="stock_disponible", new_name="stock",
        ),
        migrations.RemoveField(model_name="producto", name="precio_compra",),
        migrations.RemoveField(model_name="producto", name="stock_inicial",),
        migrations.RemoveField(model_name="producto", name="ventas",),
    ]
